Repository wrenfold/wrenfold, pull requests merged in 2024-11, with the labels that each got.

#284 Improve performance of multiplications
  components/core/benchmarks/bench_jacobian.cc
  components/core/tests/scalar_operations_test.cc
  components/core/wf/code_generation/ir_form_visitor.cc
  components/core/wf/collect.cc
  components/core/wf/constants.cc
  components/core/wf/constants.h
  components/core/wf/expression.cc
  components/core/wf/expression_visitor.h
  components/core/wf/expressions/addition.cc
  components/core/wf/expressions/custom_type_expressions.cc
  components/core/wf/expressions/multiplication.cc
  components/core/wf/expressions/multiplication.h
  components/core/wf/external_function.cc
  components/core/wf/number_set.cc
  components/core/wf/plain_formatter.cc
  components/core/wf/substitute.cc
  components/wrapper/pywrenfold/sympy_conversion.cc
Labels: performance

#285 Add `convert_ternaries` option to allow conditionals to remain in ternary form
  components/core/benchmarks/bench_code_generation.cc
  components/core/test_support/wf_test_support/code_gen_helpers.h
  components/core/tests/cpp_generation_gen.cc
  components/core/tests/cpp_generation_test.cc
  components/core/tests/rust_generation_gen.cc
  components/core/tests/rust_generation_test/src/generated.rs
  components/core/tests/rust_generation_test/src/lib.rs
  components/core/tests/rust_generation_test_2/src/generated.rs
  components/core/tests/test_expressions_codegen.h
  components/core/wf/code_generation/ast.h
  components/core/wf/code_generation/ast_conversion.cc
  components/core/wf/code_generation/ast_conversion.h
  components/core/wf/code_generation/ast_element.h
  components/core/wf/code_generation/ast_formatters.h
  components/core/wf/code_generation/control_flow_graph.cc
  components/core/wf/code_generation/control_flow_graph.h
  components/core/wf/code_generation/cpp_code_generator.cc
  components/core/wf/code_generation/cpp_code_generator.h
  components/core/wf/code_generation/ir_control_flow_converter.cc
  components/core/wf/code_generation/ir_control_flow_converter.h
  components/core/wf/code_generation/ir_value.cc
  components/core/wf/code_generation/rust_code_generator.cc
  components/core/wf/code_generation/rust_code_generator.h
  components/core/wf/enumerations.h
  components/core/wf/utility/strings.h
  components/python/wrenfold/code_generation.py
  components/wrapper/pywrenfold/ast_wrapper.cc
  components/wrapper/pywrenfold/codegen_wrapper.cc
  components/wrapper/pywrenfold/docs/codegen_wrapper.h
Labels: feature

#287 Remove unnecessary parentheses around numeric negative literals in code generation
  components/core/tests/rust_generation_test/src/generated.rs
  components/core/wf/code_generation/ir_value.cc
Labels: bug

#290 Add `stop_derivative` expression type
  components/core/CMakeLists.txt
  components/core/test_support/wf_test_support/test_macros.h
  components/core/tests/derivatives_test.cc
  components/core/tests/ir_conversion_test.cc
  components/core/tests/plain_formatter_test.cc
  components/core/tests/scalar_operations_test.cc
  components/core/wf/code_generation/ir_form_visitor.cc
  components/core/wf/code_generation/ir_form_visitor.h
  components/core/wf/derivative.cc
  components/core/wf/derivative.h
  components/core/wf/expression.cc
  components/core/wf/expression.h
  components/core/wf/expressions/all_expressions.h
  components/core/wf/expressions/stop_derivative.cc
  components/core/wf/expressions/stop_derivative.h
  components/core/wf/functions.cc
  components/core/wf/functions.h
  components/core/wf/number_set.cc
  components/core/wf/plain_formatter.cc
  components/core/wf/plain_formatter.h
  components/core/wf/tree_formatter.cc
  components/core/wf/tree_formatter.h
  components/wrapper/pywrenfold/docs/scalar_wrapper.h
  components/wrapper/pywrenfold/scalar_wrapper.cc
  components/wrapper/tests/expression_wrapper_test.py
  examples/imu_integration/imu_integration_test.cc
Labels: feature

#291 Add C99 generation example + an example of Kannala-Brandt camera model
  CMakeLists.txt
  docs/source/reference/new_language.rst
  examples/CMakeLists.txt
  examples/__init__.py
  examples/c_generation/CMakeLists.txt
  examples/c_generation/README.md
  examples/c_generation/c_code_generator.py
  examples/c_generation/c_generation.c
  examples/c_generation/c_generation.py
  examples/c_generation/c_generation_test.cc
  examples/c_generation/c_span_types.h
  examples/shared_expressions.py
  support/test_wheel.py
Labels: feature

#292 Fix bug where nested matrix in custom type resulted in segfault
  components/core/tests/cpp_generation_gen.cc
  components/core/tests/cpp_generation_test.cc
  components/core/tests/rust_generation_gen.cc
  components/core/tests/rust_generation_test/src/generated.rs
  components/core/tests/rust_generation_test/src/types.rs
  components/core/tests/test_expressions.h
  components/core/tests/test_expressions_codegen.h
  components/core/wf/code_generation/ast_conversion.cc
  components/core/wf/code_generation/ast_visitor.h
Labels: bug

#288 Add Python code generation for PyTorch, JAX, and NumPy
  .github/workflows/ci.yml
  components/core/CMakeLists.txt
  components/core/wf/code_generation/ast_element.h
  components/core/wf/code_generation/cpp_code_generator.cc
  components/core/wf/code_generation/expression_group.h
  components/core/wf/code_generation/function_description.cc
  components/core/wf/code_generation/function_description.h
  components/core/wf/code_generation/python_code_generator.cc
  components/core/wf/code_generation/python_code_generator.h
  components/core/wf/code_generation/rust_code_generator.cc
  components/core/wf/external_function.cc
  components/core/wf/external_function.h
  components/core/wf/substitute.cc
  components/python/wrenfold/code_generation.py
  components/wrapper/CMakeLists.txt
  components/wrapper/pywrenfold/ast_wrapper.cc
  components/wrapper/pywrenfold/code_formatting_wrapper.cc
  components/wrapper/pywrenfold/codegen_wrapper.cc
  components/wrapper/tests/CMakeLists.txt
  components/wrapper/tests/external_function_wrapper_test.py
  components/wrapper/tests/python_code_generation_test.py
  docs/source/building.rst
  docs/source/python_api/ast.rst
  docs/source/python_api/code_generation.rst
  examples/python_generation/README.md
  examples/python_generation/python_generation.py
  examples/rosenbrock/rosenbrock.py
  linux-environment.yml
  pyproject.toml
  requirements.txt
  support/conda/wrenfold/meta.yaml
  support/requirements.in
  support/testing-requirements.in
Labels: feature

#294 Add example of generating KB camera model and invoking it w/ JAX
  examples/CMakeLists.txt
  examples/jax_camera_model/CMakeLists.txt
  examples/jax_camera_model/README.md
  examples/jax_camera_model/jax_camera_model.py
  examples/shared_expressions.py
Labels: feature

#295 Add basic contributing.md
  CONTRIBUTING.md
Labels: documentation

#296 Add code coverage github action
  .github/workflows/coverage.yml
  CMakeLists.txt
  README.md
  components/core/CMakeLists.txt
  components/core/tests/cpp_generation_test.cc
  components/runtime/CMakeLists.txt
  docs/PACKAGE_README.md
  examples/c_generation/c_span_types.h
  support/print_coverage.py
Labels: feature

#302 Add apply_preamble to the python code generator
  components/core/wf/code_generation/python_code_generator.cc
  components/core/wf/code_generation/python_code_generator.h
  components/wrapper/pywrenfold/code_formatting_wrapper.cc
  components/wrapper/tests/python_code_generation_test.py
Labels: feature

#304 Do not set git hash at build time if we failed to obtain it
  components/wrapper/CMakeLists.txt
Labels: bug
